# -*- coding: utf-8 -*-
"""Trial New

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/175PxMljlm7mEIPzXXt2hZpFpQzvm9G41
"""

# -*- coding: utf-8 -*-
"""working run

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14rv03MFz-nbToyjrzrSbfA-oVZi9VMOR
"""

# Mount Google Drive
from google.colab import drive
drive.mount('/content/drive')

# Install PyTorch (Colab usually has this, but we'll ensure it's the right version)
!pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118

# Install PyTorch Geometric
!pip install torch-geometric

# Install additional dependencies for PyTorch Geometric
import torch
print(f"PyTorch version: {torch.__version__}")

# Get the correct torch version for installing scatter and sparse
torch_version = torch.__version__.split('+')[0]
cuda_version = torch.__version__.split('+')[1] if '+' in torch.__version__ else 'cpu'

!pip install torch-scatter torch-sparse -f https://data.pyg.org/whl/torch-{torch_version}+{cuda_version}.html

print("\n✅ Installation complete!")
print("⚠️  Please restart the runtime now: Runtime → Restart runtime")
print("Then continue with the next cell.")

# Standard libraries
import os
import glob
import random
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from tqdm import tqdm
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import warnings
warnings.filterwarnings('ignore')

# PyTorch
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.optim import Adam

# PyTorch Geometric
from torch_geometric.data import Data, DataLoader
from torch_geometric.nn import GCNConv, global_mean_pool

# Set random seeds for reproducibility
torch.manual_seed(42)
np.random.seed(42)
random.seed(42)

print("✅ Libraries imported successfully!")
print(f"PyTorch version: {torch.__version__}")
print(f"CUDA available: {torch.cuda.is_available()}")
if torch.cuda.is_available():
    print(f"CUDA device: {torch.cuda.get_device_name(0)}")

# ⚠️ UPDATE THESE PATHS TO YOUR GOOGLE DRIVE LOCATIONS ⚠️
TRAIN_DATA_ROOT = "/content/drive/MyDrive/lattice_data/Randomness_Sweep"
PREDICT_DATA_ROOT = "/content/drive/MyDrive/lattice_data/Lattice_Guess"

# Model hyperparameters (optimized for ~1000 samples)
BATCH_SIZE = 16
HIDDEN_DIM = 24  # Small to prevent overfitting
DEVICE = 'cuda' if torch.cuda.is_available() else 'cpu'

# ── Two-Phase Learning Rate Schedule ──────────────────────────────────────────
# Phase 1 (Exploration): Large LR scans the loss landscape fast and escapes
#   local minima, finding the "Goldilocks zone" for the optimizer to land in.
# Phase 2 (Fine-tuning): Small LR then drills down precisely from that region.
# ──────────────────────────────────────────────────────────────────────────────
LR_PHASE1       = 0.003    # Large LR  — coarse exploration
LR_PHASE2       = 0.0005  # Small LR  — fine convergence
EPOCHS_PHASE1   = 200     # Epochs at large LR
EPOCHS_PHASE2   = 700     # Epochs at small LR
NUM_EPOCHS      = EPOCHS_PHASE1 + EPOCHS_PHASE2
PATIENCE        = 999     # Early stopping
print(f"✅ Configuration set:")
print(f"  Device: {DEVICE}")
print(f"  Training data: {TRAIN_DATA_ROOT}")
print(f"  Prediction data: {PREDICT_DATA_ROOT}")
print(f"  Batch size: {BATCH_SIZE}")
print(f"  Hidden dimension: {HIDDEN_DIM}")
print(f"  Phase 1 — LR: {LR_PHASE1}  |  Epochs: {EPOCHS_PHASE1}  (exploration)")
print(f"  Phase 2 — LR: {LR_PHASE2}  |  Epochs: {EPOCHS_PHASE2}  (fine-tune)")
print(f"  Total epochs: {NUM_EPOCHS}")
print(f"  Early stopping patience: {PATIENCE}")

class SimpleGNN(nn.Module):
    """
    Two-layer Graph Convolutional Network for lattice stiffness prediction.
    """
    def __init__(self, input_dim, hidden_dim=32, output_dim=1):
        super(SimpleGNN, self).__init__()

        # First graph convolution layer
        self.conv1 = GCNConv(input_dim, hidden_dim)
        self.bn1 = nn.BatchNorm1d(hidden_dim)

        # ← ADD THIS: Second graph convolution layer
        self.conv2 = GCNConv(hidden_dim, hidden_dim)
        self.bn2 = nn.BatchNorm1d(hidden_dim)

        # Output layer
        self.fc_out = nn.Linear(hidden_dim, output_dim)
        self.dropout = nn.Dropout(0.1)

    def forward(self, data):
        x, edge_index, batch = data.x, data.edge_index, data.batch

        # First layer: Graph convolution + activation
        x = self.conv1(x, edge_index)
        x = self.bn1(x)
        x = F.relu(x)
        x = self.dropout(x)

        # ← ADD THIS: Second layer
        x = self.conv2(x, edge_index)
        x = self.bn2(x)
        x = F.relu(x)
        x = self.dropout(x)

        # Global pooling
        x = global_mean_pool(x, batch)

        # Final prediction
        out = self.fc_out(x)

        return out

print("✅ Model class defined!")

def load_lattice_data(folder_path):
    """
    Load a single lattice sample from CSV files.
    """
    # Load node features
    node_features_path = os.path.join(folder_path, 'node_features.csv')
    nodes_df = pd.read_csv(node_features_path)
    node_features = nodes_df[['x', 'y']].values.astype(np.float32)

    # Load adjacency matrix
    adj_path = os.path.join(folder_path, 'adjacency_area.csv')
    adj_df = pd.read_csv(adj_path, index_col=0)
    adj_matrix = adj_df.values

    # Convert to edge list (bidirectional)
    edge_list = []
    for i in range(adj_matrix.shape[0]):
        for j in range(i+1, adj_matrix.shape[1]):
            if adj_matrix[i, j] == 1:
                edge_list.append([i, j])
                edge_list.append([j, i])

    edge_index = torch.tensor(edge_list, dtype=torch.long).t().contiguous()

    # Load stiffness
    stiffness_path = os.path.join(folder_path, 'lattice_stiffness.csv')
    stiffness_df = pd.read_csv(stiffness_path)
    stiffness = stiffness_df.iloc[0, 0]

    # Create graph
    data = Data(
        x=torch.tensor(node_features, dtype=torch.float32),
        edge_index=edge_index,
        y=torch.tensor([stiffness], dtype=torch.float32)
    )

    return data


def load_all_lattices(data_root):
    """
    Load all lattice samples from directory.
    """
    all_data = []
    randomness_folders = glob.glob(os.path.join(data_root, 'randomness_*'))
    random.shuffle(randomness_folders)  # Shuffle so loading order is random, not sequential

    print(f"Found {len(randomness_folders)} lattice samples in {data_root}")

    for folder in tqdm(randomness_folders, desc="Loading lattices"):
        try:
            data = load_lattice_data(folder)
            all_data.append(data)
        except Exception as e:
            print(f"⚠️  Error loading {folder}: {e}")

    return all_data

print("✅ Data loading functions defined!")

# Load all training data
print("📁 Loading training data...\n")
all_data = load_all_lattices(TRAIN_DATA_ROOT)
print(f"\n✅ Total samples loaded: {len(all_data)}")

# Split data — shuffle=True ensures random ordering before splitting
random.shuffle(all_data)  # Extra shuffle after loading for good measure
train_data, temp_data = train_test_split(all_data, train_size=0.8, shuffle=True)
val_data, test_data = train_test_split(temp_data, train_size=0.5, shuffle=True)

print(f"\n📊 Data Split:")
print(f"  Training:   {len(train_data)} samples (80%)")
print(f"  Validation: {len(val_data)} samples (10%)")
print(f"  Test:       {len(test_data)} samples (10%)")

# Show example graph
example = train_data[0]
print(f"\n🔍 Example graph structure:")
print(f"  Nodes: {example.x.shape[0]}")
print(f"  Edges: {example.edge_index.shape[1]}")
print(f"  Node features: {example.x.shape[1]} (x, y coordinates)")
print(f"  Target stiffness: {example.y.item():.6f} N/mm")

def normalize_features(train_data, val_data, test_data):
    """Normalize features using training set statistics."""
    train_features = torch.cat([data.x for data in train_data], dim=0).numpy()

    scaler = StandardScaler()
    scaler.fit(train_features)

    for data in train_data:
        data.x = torch.tensor(scaler.transform(data.x.numpy()), dtype=torch.float32)

    for data in val_data:
        data.x = torch.tensor(scaler.transform(data.x.numpy()), dtype=torch.float32)

    for data in test_data:
        data.x = torch.tensor(scaler.transform(data.x.numpy()), dtype=torch.float32)

    return train_data, val_data, test_data, scaler

train_data, val_data, test_data, scaler = normalize_features(train_data, val_data, test_data)
print("✅ Features normalized!")
print(f"  Scaler mean: {scaler.mean_}")
print(f"  Scaler std: {scaler.scale_}")

train_loader = DataLoader(train_data, batch_size=BATCH_SIZE, shuffle=True)
val_loader = DataLoader(val_data, batch_size=BATCH_SIZE, shuffle=False)
test_loader = DataLoader(test_data, batch_size=BATCH_SIZE, shuffle=False)

print(f"✅ Data loaders created:")
print(f"  Training batches: {len(train_loader)}")
print(f"  Validation batches: {len(val_loader)}")
print(f"  Test batches: {len(test_loader)}")

input_dim = train_data[0].x.shape[1]  # 2 (x, y coordinates)
model = SimpleGNN(input_dim=input_dim, hidden_dim=HIDDEN_DIM, output_dim=1)

# Count parameters
num_params = sum(p.numel() for p in model.parameters() if p.requires_grad)

print(f"🧠 Model: SimpleGNN (Single-Layer)")
print(f"  Input dimension: {input_dim}")
print(f"  Hidden dimension: {HIDDEN_DIM}")
print(f"  Total trainable parameters: {num_params:,}")
print(f"  Parameters/Data ratio: {num_params/len(all_data):.2f}")
print(f"\n📋 Model architecture:")
print(model)

def train_model(model, train_loader, val_loader, optimizer, criterion,
                num_epochs=200, device='cpu', patience=20):
    """
    Two-phase training:
      Phase 1 — large LR (exploration): quickly scans the loss landscape and
                escapes local minima to find the Goldilocks region.
      Phase 2 — small LR (fine-tune):  converges precisely from that region.

    The optimizer is re-initialised between phases so the momentum/state
    from the noisy large-LR phase doesn't carry over and destabilise fine-tuning.
    """
    model.to(device)

    train_losses = []
    val_losses   = []
    best_val_loss      = float('inf')
    best_model_state   = None
    patience_counter   = 0

    phases = [
        ("Phase 1 — Exploration (large LR)", LR_PHASE1,  EPOCHS_PHASE1),
        ("Phase 2 — Fine-tune  (small LR)",  LR_PHASE2,  EPOCHS_PHASE2),
    ]

    global_epoch = 0

    for phase_name, lr, phase_epochs in phases:
        print(f"\n{'='*60}")
        print(f"🚀 {phase_name}  |  LR={lr}  |  Epochs={phase_epochs}")
        print(f"{'='*60}")

        # Fresh optimizer each phase — prevents stale momentum from phase 1
        # polluting the precise descent in phase 2
        phase_optimizer = Adam(model.parameters(), lr=lr, weight_decay=1e-5)

        patience_counter = 0  # Reset patience per phase

        for epoch in range(phase_epochs):
            # ── Training ──────────────────────────────────────────────────────
            model.train()
            train_loss = 0
            for batch in train_loader:
                batch = batch.to(device)
                phase_optimizer.zero_grad()
                out  = model(batch)
                loss = criterion(out, batch.y.unsqueeze(1))
                loss.backward()
                phase_optimizer.step()
                train_loss += loss.item() * batch.num_graphs

            train_loss /= len(train_loader.dataset)
            train_losses.append(train_loss)

            # ── Validation ────────────────────────────────────────────────────
            model.eval()
            val_loss = 0
            with torch.no_grad():
                for batch in val_loader:
                    batch = batch.to(device)
                    out   = model(batch)
                    loss  = criterion(out, batch.y.unsqueeze(1))
                    val_loss += loss.item() * batch.num_graphs

            val_loss /= len(val_loader.dataset)
            val_losses.append(val_loss)

            # ── Best model checkpoint ─────────────────────────────────────────
            if val_loss < best_val_loss:
                best_val_loss    = val_loss
                patience_counter = 0
                best_model_state = {k: v.clone() for k, v in model.state_dict().items()}
            else:
                patience_counter += 1

            global_epoch += 1
            if global_epoch % 20 == 0:
                print(f'  Epoch {global_epoch}/{num_epochs} '
                      f'| Train: {train_loss:.6f} | Val: {val_loss:.6f}'
                      f'{"  ★" if patience_counter == 0 else ""}')

            if patience_counter >= patience:
                print(f'  ⏹️  Early stopping at epoch {global_epoch}')
                break

        print(f"  ✅ {phase_name} done. Best val loss so far: {best_val_loss:.6f}")

    # Restore best weights found across both phases
    model.load_state_dict(best_model_state)

    return {
        'train_losses': train_losses,
        'val_losses':   val_losses,
        'best_val_loss': best_val_loss
    }

print("✅ Training function defined!")

# Optimizer is created per-phase inside train_model — no single LR needed here
criterion = nn.MSELoss()

print("🚀 Starting two-phase training...\n")
print("="*60)
history = train_model(
    model, train_loader, val_loader,
    optimizer=None,   # unused — phases create their own optimizers
    criterion=criterion,
    num_epochs=NUM_EPOCHS, device=DEVICE, patience=PATIENCE
)
print("="*60)
print(f"\n✅ Training complete!")
print(f"  Best validation loss: {history['best_val_loss']:.6f}")

def evaluate_model(model, data_loader, device='cpu'):
    """
    Evaluate model performance.
    """
    model.eval()
    model.to(device)

    predictions = []
    ground_truth = []

    with torch.no_grad():
        for batch in data_loader:
            batch = batch.to(device)
            out = model(batch)
            predictions.extend(out.cpu().numpy().flatten())
            ground_truth.extend(batch.y.cpu().numpy().flatten())

    predictions = np.array(predictions)
    ground_truth = np.array(ground_truth)

    # Calculate metrics
    mse = np.mean((predictions - ground_truth) ** 2)
    rmse = np.sqrt(mse)
    mae = np.mean(np.abs(predictions - ground_truth))
    relative_errors = np.abs((predictions - ground_truth) / ground_truth) * 100
    mean_relative_error = np.mean(relative_errors)

    metrics = {
        'MSE': mse,
        'RMSE': rmse,
        'MAE': mae,
        'Mean Relative Error (%)': mean_relative_error
    }

    return predictions, ground_truth, metrics

print("✅ Evaluation function defined!")

print("📊 Evaluating model...\n")

train_pred, train_true, train_metrics = evaluate_model(model, train_loader, DEVICE)
val_pred, val_true, val_metrics = evaluate_model(model, val_loader, DEVICE)
test_pred, test_true, test_metrics = evaluate_model(model, test_loader, DEVICE)

print("="*60)
print("📈 Training Set Performance:")
print("="*60)
for key, value in train_metrics.items():
    print(f"  {key}: {value:.6f}")

print("\n" + "="*60)
print("📊 Validation Set Performance:")
print("="*60)
for key, value in val_metrics.items():
    print(f"  {key}: {value:.6f}")

print("\n" + "="*60)
print("🎯 Test Set Performance:")
print("="*60)
for key, value in test_metrics.items():
    print(f"  {key}: {value:.6f}")
print("="*60)

# Training history — with phase boundary marker
plt.figure(figsize=(10, 5))
plt.plot(history['train_losses'], label='Training Loss', linewidth=2)
plt.plot(history['val_losses'], label='Validation Loss', linewidth=2)
plt.axvline(x=EPOCHS_PHASE1, color='gray', linestyle='--', linewidth=1.5,
            label=f'Phase switch (epoch {EPOCHS_PHASE1})\nLR {LR_PHASE1} → {LR_PHASE2}')
plt.xlabel('Epoch', fontsize=12)
plt.ylabel('MSE Loss', fontsize=12)
plt.title('Training History (Two-Phase LR)', fontsize=14, fontweight='bold')
plt.legend(fontsize=11)
plt.grid(True, alpha=0.3)
plt.tight_layout()
plt.show()

# Predictions vs Ground Truth
fig, axes = plt.subplots(1, 3, figsize=(18, 5))

datasets = [
    (train_pred, train_true, 'Training Set', 'blue'),
    (val_pred, val_true, 'Validation Set', 'orange'),
    (test_pred, test_true, 'Test Set', 'green')
]

for ax, (pred, true, title, color) in zip(axes, datasets):
    ax.scatter(true, pred, alpha=0.6, s=50, c=color)

    min_val = min(true.min(), pred.min())
    max_val = max(true.max(), pred.max())
    ax.plot([min_val, max_val], [min_val, max_val], 'r--', lw=2, label='Perfect Prediction')

    r2 = 1 - np.sum((true - pred)**2) / np.sum((true - true.mean())**2)

    ax.set_xlabel('Ground Truth Stiffness (N/mm)', fontsize=11)
    ax.set_ylabel('Predicted Stiffness (N/mm)', fontsize=11)
    ax.set_title(f'{title}\nR² = {r2:.4f}', fontsize=12, fontweight='bold')
    ax.legend(fontsize=10)
    ax.grid(True, alpha=0.3)

plt.tight_layout()
plt.show()

def predict_on_new_lattices(model, data_root, scaler, device='cpu'):
    """
    Make predictions on new lattices and compare with actual stiffness.
    """
    print("\n" + "="*60)
    print("🔮 MAKING PREDICTIONS ON NEW LATTICES")
    print("="*60)
    print("📁 Loading new lattices...\n")

    new_data = load_all_lattices(data_root)

    # Normalize
    for data in new_data:
        data.x = torch.tensor(scaler.transform(data.x.numpy()), dtype=torch.float32)

    new_loader = DataLoader(new_data, batch_size=1, shuffle=False)

    # Predict
    predictions, ground_truth, metrics = evaluate_model(model, new_loader, device)

    # Results
    percent_diff = np.abs((predictions - ground_truth) / ground_truth) * 100

    print(f"\n" + "="*60)
    print(f"📊 Prediction Results on {len(new_data)} new lattices:")
    print("="*60)
    print(f"  Mean Absolute Error (MAE): {metrics['MAE']:.6f} N/mm")
    print(f"  Root Mean Square Error (RMSE): {metrics['RMSE']:.6f} N/mm")
    print(f"  Mean Relative Error: {metrics['Mean Relative Error (%)']:.2f}%")
    print(f"  Max Relative Error: {percent_diff.max():.2f}%")
    print(f"  Min Relative Error: {percent_diff.min():.2f}%")
    print("="*60)

    return predictions, ground_truth, metrics, percent_diff

# Run predictions
new_pred, new_true, new_metrics, new_percent_diff = predict_on_new_lattices(
    model, PREDICT_DATA_ROOT, scaler, DEVICE
)

# Visualize predictions on new lattices
fig, axes = plt.subplots(1, 2, figsize=(14, 5))

# Predictions vs Actual
axes[0].scatter(new_true, new_pred, alpha=0.6, s=100, c='purple', edgecolors='black', linewidth=0.5)
min_val = min(new_true.min(), new_pred.min())
max_val = max(new_true.max(), new_pred.max())
axes[0].plot([min_val, max_val], [min_val, max_val], 'r--', lw=2, label='Perfect Prediction')
axes[0].set_xlabel('Actual Stiffness (N/mm)', fontsize=12)
axes[0].set_ylabel('Predicted Stiffness (N/mm)', fontsize=12)
axes[0].set_title('Predictions on New Lattices', fontsize=14, fontweight='bold')
axes[0].legend(fontsize=11)
axes[0].grid(True, alpha=0.3)

# Percent Difference
axes[1].bar(range(len(new_percent_diff)), new_percent_diff, alpha=0.7, edgecolor='black', color='coral')
axes[1].axhline(y=new_metrics['Mean Relative Error (%)'], color='red',
               linestyle='--', linewidth=2, label=f"Mean: {new_metrics['Mean Relative Error (%)']:.2f}%")
axes[1].set_xlabel('Lattice Index', fontsize=12)
axes[1].set_ylabel('Percent Difference (%)', fontsize=12)
axes[1].set_title('Prediction Error by Lattice', fontsize=14, fontweight='bold')
axes[1].legend(fontsize=11)
axes[1].grid(True, alpha=0.3, axis='y')

plt.tight_layout()
plt.show()

# Save detailed prediction results
results_df = pd.DataFrame({
    'Lattice_Index': range(len(new_pred)),
    'Predicted_Stiffness': new_pred,
    'Actual_Stiffness': new_true,
    'Absolute_Error': np.abs(new_pred - new_true),
    'Percent_Difference': new_percent_diff
})

results_df.to_csv('prediction_results.csv', index=False)
print("✅ Results saved to: prediction_results.csv")
print("\n📊 First 10 predictions:")
print(results_df)

# Save model
torch.save({
    'model_state_dict': model.state_dict(),
    'scaler': scaler,
    'input_dim': input_dim,
    'hidden_dim': HIDDEN_DIM,
    'train_metrics': train_metrics,
    'val_metrics': val_metrics,
    'test_metrics': test_metrics,
    'history': history
}, 'lattice_gnn_model.pt')

print("✅ Model saved to: lattice_gnn_model.pt")
print("\n🎉 All done! Your model is trained and ready to use.")

# Check the distribution of stiffness in training vs test
import matplotlib.pyplot as plt

# Training data stiffness
train_stiffness = [data.y.item() for data in train_data]
# Test data stiffness
test_stiffness = [data.y.item() for data in test_data]
# New lattice stiffness
new_stiffness = [0.036459, 0.036582, 0.038284, 0.041122, 0.029801,
                 0.042758, 0.037395, 0.034638, 0.037637, 0.027826]

print(f"Training stiffness range: {min(train_stiffness):.6f} to {max(train_stiffness):.6f}")
print(f"Training mean: {np.mean(train_stiffness):.6f}")
print(f"New lattice range: {min(new_stiffness):.6f} to {max(new_stiffness):.6f}")
print(f"New lattice mean: {np.mean(new_stiffness):.6f}")

# Plot distributions
plt.figure(figsize=(12, 4))

plt.subplot(1, 3, 1)
plt.hist(train_stiffness, bins=30, alpha=0.7, label='Training')
plt.axvline(np.mean(train_stiffness), color='red', linestyle='--', label='Mean')
plt.xlabel('Stiffness')
plt.title('Training Distribution')
plt.legend()

plt.subplot(1, 3, 2)
plt.hist(new_stiffness, bins=10, alpha=0.7, color='orange', label='New Lattices')
plt.axvline(np.mean(train_stiffness), color='red', linestyle='--', label='Training Mean')
plt.xlabel('Stiffness')
plt.title('New Lattice Distribution')
plt.legend()

plt.subplot(1, 3, 3)
# Scatter: actual vs predicted
plt.scatter(new_stiffness, [0.028553]*10, alpha=0.6, s=100)
plt.plot([0.027, 0.043], [0.027, 0.043], 'r--', label='Perfect')
plt.xlabel('Actual Stiffness')
plt.ylabel('Predicted Stiffness')
plt.title('Your Model Predictions')
plt.legend()

plt.tight_layout()
plt.show()


## 💡 **What This Tells Us:**

### If training mean ≈ 0.028-0.030:
###Your model is **not learning anything** - its just predicting the training set average for every sample. This is called **regression to the mean** and happens when:

#1. Model is too simple to capture patterns
#2. Learning rate is too high (jumping around)
#3. Training data doesn't have enough variation
#4. Features aren't informative enough

### The Pattern in Your Errors:
#Sample 0: 0.036459 actual → 0.028553 pred = 21.7% error (far from mean)
#Sample 1: 0.036582 actual → 0.027771 pred = 24.1% error (far from mean)
#Sample 4: 0.029801 actual → 0.030272 pred = 1.6% error  ← CLOSE TO MEAN!
#Sample 9: 0.027826 actual → 0.028365 pred = 1.9% error  ← CLOSE TO MEAN!